[profile.default]
src = "src"
out = "out"
libs = ["../lib"]
remappings = [
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/",
    "forge-std/=../lib/forge-std/src/"
]

# Exclude problematic Certora files from compilation
test = "test"
exclude = [
    "../lib/openzeppelin-contracts/certora/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
